# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      MYSQL_DATABASE: employee
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
        PMA_HOST: mysql-service
    ports:
      - "8081:80"
    depends_on:
      - mysql-service
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge
